drop table rezultat;
drop table staza;
drop table vozac;
drop table drzava;

CREATE TABLE DRZAVA (
  IDD INTEGER NOT NULL,
  NAZIVD VARCHAR2(128) NOT NULL,
  CONSTRAINT PK_DRZAVA PRIMARY KEY (IDD)
);

CREATE TABLE VOZAC (
  IDV INTEGER NOT NULL,
  IMEV VARCHAR2(128) NOT NULL,
  PREZV VARCHAR2(128) NOT NULL,
  GODRODJ INTEGER NOT NULL,
  BROJTIT INTEGER,
  DRZV INTEGER,
  CONSTRAINT PK_VOZAC PRIMARY KEY (IDV),
  CONSTRAINT FK_VOZAC_DRZAVA FOREIGN KEY (DRZV) REFERENCES DRZAVA (IDD)
);

CREATE TABLE STAZA (
  IDS INTEGER NOT NULL,
  NAZIVS VARCHAR2(128) NOT NULL,
  BROJKRUG INTEGER NOT NULL,
  DUZKRUG DECIMAL(5,2),
  DRZS INTEGER,
  CONSTRAINT PK_STAZA PRIMARY KEY (IDS),
  CONSTRAINT FK_STAZA_DRZAVA FOREIGN KEY (DRZS) REFERENCES DRZAVA (IDD)
);

CREATE TABLE REZULTAT (
  IDR CHAR(3) NOT NULL,
  IDV INTEGER NOT NULL,
  IDS INTEGER NOT NULL,
  SEZONA INTEGER NOT NULL,
  PLASMAN INTEGER,
  BODOVI INTEGER,
  MAKSBRZINA DECIMAL(5,2) NOT NULL,
  CONSTRAINT PK_REZULTAT PRIMARY KEY (IDR),
  CONSTRAINT FK_REZULTAT_VOZAC FOREIGN KEY (IDV) REFERENCES VOZAC (IDV),
  CONSTRAINT FK_REZULTAT_STAZA FOREIGN KEY (IDS) REFERENCES STAZA (IDS),
  CONSTRAINT CH_SEZONA CHECK (SEZONA > 1949 AND SEZONA < 2020 )
);